name: My First CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      coolestStudent:
        description: "Heyo who the cool student"
        required: true


jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello Worlddddd"
      - name: Print Hello Diogo
        run: echo "Hello Diogo"