name: My First CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      coolestStudent:
        description: "Heyo who the cool student"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello Worlddddd"
      - name: Greet the Coolest Student
        run: echo "Hello ${{ inputs.coolestStudent || 'anonymous' }}!!!"
        
      - name: Listing stuff
        run: ls -la

      - name: Docker build
        run: docker build -t pokfinner/cuddly-octo-spork:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker push
        run: docker push pokfinner/cuddly-octo-spork:latest